- name: Enable RDP + Auto Login + Fix NLA
  run: |
    # Enable RDP
    Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
    Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    net user runneradmin GitHub123!

    # Disable NLA
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0

    # Pastikan port 3389 terbuka
    netsh advfirewall firewall add rule name="RDP3389" dir=in action=allow protocol=TCP localport=3389

    # Start RDP services
    Set-Service -Name TermService -StartupType Automatic
    Start-Service -Name TermService

    # Auto login registry
    New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "AutoAdminLogon" -Value "1" -PropertyType String -Force
    New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "DefaultUsername" -Value "runneradmin" -PropertyType String -Force
    New-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" -Name "DefaultPassword" -Value "GitHub123!" -PropertyType String -Force

    # Cek port 3389 listening
    netstat -ano | findstr 3389
