name: Windows RDP with Tailscale

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest   # Bisa diganti windows-2022 kalau mau fix
    steps:
      - name: Install Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile "tailscale.msi"
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn' -NoNewWindow -Wait
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TS_AUTHKEY --accept-routes --hostname github-rdp
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

      - name: Enable RDP
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Show Tailscale IP
        run: |
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
