name: Windows RDP with Tailscale (Keep Alive)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Install & Connect Tailscale
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile "tailscale.msi"
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn' -NoNewWindow -Wait
          Start-Sleep -Seconds 10
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $env:TS_AUTHKEY --accept-routes --accept-dns=false --hostname github-rdp-${env:GITHUB_RUN_ID}
          & "C:\Program Files\Tailscale\tailscale.exe" ip -4
        env:
          TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}

      - name: Enable RDP + Set Password + Disable NLA
        run: |
          Set-ItemProperty -Path "HKLM:\System\CurrentControlSet\Control\Terminal Server" -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin GitHub123!
          Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" -Name "UserAuthentication" -Value 0
          netsh advfirewall firewall add rule name="RDP3389" dir=in action=allow protocol=TCP localport=3389
          Set-Service -Name TermService -StartupType Automatic
          Start-Service -Name TermService
          netstat -ano | findstr 3389

      - name: Confirm RDP Ready
        shell: cmd
        run: |
          query user
          exit /b 0

      - name: Keep Alive (infinite)
        shell: cmd
        run: |
          echo RDP session running. Do not close this workflow.
          ping -t 127.0.0.1 >nul
